// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2mk4dcD7RqqbMP7UfHb0zvz6qtAxcb40',
    appId: '1:311444294486:web:6b0851472a1b0ee0e7e4f7',
    messagingSenderId: '311444294486',
    projectId: 'tetris-game-firebase',
    authDomain: 'tetris-game-firebase.firebaseapp.com',
    storageBucket: 'tetris-game-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC667LBkwTBBPr2Sp41EEiliVQ_gdRmcAI',
    appId: '1:311444294486:android:5c5b3df06ba53f86e7e4f7',
    messagingSenderId: '311444294486',
    projectId: 'tetris-game-firebase',
    storageBucket: 'tetris-game-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwmP6DcT2pMwfkptIGSYP-e27qXYRe9p4',
    appId: '1:311444294486:ios:7b03168779130d0ee7e4f7',
    messagingSenderId: '311444294486',
    projectId: 'tetris-game-firebase',
    storageBucket: 'tetris-game-firebase.appspot.com',
    iosBundleId: 'com.example.tetrisGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwmP6DcT2pMwfkptIGSYP-e27qXYRe9p4',
    appId: '1:311444294486:ios:7b03168779130d0ee7e4f7',
    messagingSenderId: '311444294486',
    projectId: 'tetris-game-firebase',
    storageBucket: 'tetris-game-firebase.appspot.com',
    iosBundleId: 'com.example.tetrisGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2mk4dcD7RqqbMP7UfHb0zvz6qtAxcb40',
    appId: '1:311444294486:web:ac36b23ca9a6a46ee7e4f7',
    messagingSenderId: '311444294486',
    projectId: 'tetris-game-firebase',
    authDomain: 'tetris-game-firebase.firebaseapp.com',
    storageBucket: 'tetris-game-firebase.appspot.com',
  );
}
